#======================WARNING======================
# The Minimum amount of Health is 3
#
# The Maximum amount of Health is 10000
#
# Going Past these Safe Guard Limits you may find yourself Lagging, Dieing Instantly or Crashing when Attacking others or other when they attack you.
#===================================================
#

# Verbosity of console messages (low, normal, high, highest)
verbosity: normal 

# Health applied if no other permission found
defaulthealth: 20
# Health applied to OP players (as they automatically have all permission nodes)
ophealth: 20

# Add new permission nodes here - give player permissionshealth.<name> permission
permissionshealth:
  admin: 20
  
  group1: 20
  group2: 20

  mynewpermission: 200  # give player permissionshealth.mynewpermission, they get 200 health
