# Yes the values Can be changed to whatever you want for each Health1-200 Guest and Admin
#======================WARNING======================
# The Minimum amount of Health is 3
#
# The Maximum amount of Health is 10000
#
# Going Past these Safe Guard Limits you may find yourself Lagging, Dieing Instantly or Crashing when Attacking others or other when they attack you.
#===================================================
#
# Guest Health is default for anyone who does not have a permissions node


GuestHealth: 20 # permissionshealth.guest

#This Node admin & guest are the only 2 non customizable nodes

#This is also set for anyone who is OP on server
AdminHealth: 200 #permissionshealth.admin

# Add new permission nodes here - give player permissionshealth.<name> permission
permissionshealth:
  guest: 20
  admin: 20
  
  group1: 20
  group2: 20

  mynewpermission: 200  # give player permissionshealth.mynewpermission, they get 200 health
