name: PermissionsHealth
main: net.bless.ph.PermissionsHealth
version: 0.2.01
builddate: 2013/04/23 02:14
author: Bless
authors:
  - Bless
  - Zarius
commands:
    ph:
      description: PermissionsHealth admin commands
      usage: /ph help - for more info
      aliases: [phh, phr, pha, phu, php, pheal]