name: PermissionsHealth
main: net.bless.ph.PermissionsHealth
version: 0.0.71
builddate: 2013/04/12 17:39
author: Bless
commands:
    pheal:
      description: Use this to fully heal a player.
      usage: /<command> [player]
      permission: permissionshealth.pheal
      permission-message: You don't have <permission>
    phc:
      description: Use to view your current health.
      usage: /<command>
    hp:
      description: Use to view your current health.
      usage: /<command>
    pho:
      description: Use to view target's current health.
      usage: /<command>
    phreload:
      description: reload
      usage: /<command>
      permission: permissionshealth.reload
      permission-message: You don't have <permission>
permissions:
   permissionshealth.guest:
        default: true
        description: Gives Health to Guest
   permissionshealth.admin:
        description: Gives Health to Admin
        default: op